### ISSUE TITLE
Unable to use development container in VSCode

### ISSUE THREAD

**Issue by kdwk** [AparokshaUI/AdwaitaTemplate#8] opened 2024-09-14 05:17 UTC
Fails with:

```
[27 ms] Dev Containers 0.384.0 in VS Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3).
[27 ms] Start: Resolving Remote
[40 ms] Setting up container for folder or workspace: /home/kdwk/Projects/personal/AdwaitaTemplate
[54 ms] Start: Check Docker is running
[54 ms] Start: Run: podman-remote version
[183 ms] Client:       Podman Engine
Version:      5.2.0
API Version:  5.2.0
Go Version:   go1.22.6
Git Commit:   b22d5c61eef93475413724f49fd6a32980d2c746
Built:        Fri Aug  9 23:41:46 2024
OS/Arch:      linux/amd64

Server:       Podman Engine
Version:      5.1.1
API Version:  5.1.1
Go Version:   go1.22.3
Built:        Tue Jun  4 08:00:00 2024
OS/Arch:      linux/amd64
[185 ms] Start: Run: podman-remote volume ls -q
[207 ms] Start: Run: podman-remote ps -q -a --filter label=vsch.local.folder=/home/kdwk/Projects/personal/AdwaitaTemplate --filter label=vsch.quality=stable
[223 ms] Start: Run: podman-remote ps -q -a --filter label=devcontainer.local_folder=/home/kdwk/Projects/personal/AdwaitaTemplate --filter label=devcontainer.config_file=/home/kdwk/Projects/personal/AdwaitaTemplate/.devcontainer/devcontainer.json
[239 ms] Start: Run: podman-remote ps -q -a --filter label=devcontainer.local_folder=/home/kdwk/Projects/personal/AdwaitaTemplate
[251 ms] Start: Run: podman-remote ps -q -a --filter label=devcontainer.local_folder=/home/kdwk/Projects/personal/AdwaitaTemplate
[265 ms] Running Dev Containers CLI:   up --user-data-folder /home/kdwk/.var/app/com.visualstudio.code/config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman-remote --container-session-data-folder /tmp/devcontainers-f79a76fc-bb4f-4a5e-86d4-50d86ce7d1481726290809911 --workspace-folder /home/kdwk/Projects/personal/AdwaitaTemplate --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/kdwk/Projects/personal/AdwaitaTemplate --id-label devcontainer.config_file=/home/kdwk/Projects/personal/AdwaitaTemplate/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/kdwk/Projects/personal/AdwaitaTemplate/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[265 ms] Start: Run: /app/extra/vscode/code /home/kdwk/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/kdwk/.var/app/com.visualstudio.code/config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman-remote --container-session-data-folder /tmp/devcontainers-f79a76fc-bb4f-4a5e-86d4-50d86ce7d1481726290809911 --workspace-folder /home/kdwk/Projects/personal/AdwaitaTemplate --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/kdwk/Projects/personal/AdwaitaTemplate --id-label devcontainer.config_file=/home/kdwk/Projects/personal/AdwaitaTemplate/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/kdwk/Projects/personal/AdwaitaTemplate/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[409 ms] @devcontainers/cli 0.69.0. Node.js v20.15.1. linux 6.9.6-200.fc40.x86_64 x64.
[409 ms] Start: Run: podman-remote buildx version
[423 ms] buildah 1.37.0
[423 ms] 
[423 ms] Start: Run: podman-remote -v
[435 ms] Start: Resolving Remote
[436 ms] Start: Run: git rev-parse --show-cdup
[440 ms] Start: Run: podman-remote ps -q -a --filter label=devcontainer.local_folder=/home/kdwk/Projects/personal/AdwaitaTemplate --filter label=devcontainer.config_file=/home/kdwk/Projects/personal/AdwaitaTemplate/.devcontainer/devcontainer.json
[458 ms] Start: Run: podman-remote inspect --type image swift:noble
[474 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/common-utils:2'...
[474 ms] * Processing feature: ghcr.io/devcontainers/features/common-utils:2
[475 ms] Loading 149 extra certificates from /etc/ssl/certs/ca-certificates.crt.
[836 ms] Start: Run: docker-credential-secret get
[1566 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/git:1'...
[1566 ms] * Processing feature: ghcr.io/devcontainers/features/git:1
[1961 ms] * Processing feature: ghcr.io/devcontainers/features/common-utils
[2334 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers-contrib/features/curl-apt-get:1'...
[2334 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/curl-apt-get:1
[3194 ms] Files to omit: ''
[3199 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/apt-get-packages
[3577 ms] Soft-dependency 'ghcr.io/devcontainers-contrib/features/apt-get-packages' is not required.  Removing from installation order...
[3578 ms] * Fetching feature: curl-apt-get_0_oci
[4055 ms] Files to omit: ''
[4056 ms] * Fetched feature: curl-apt-get_0_oci version 1.0.16
[4056 ms] * Fetching feature: common-utils_1_oci
[4562 ms] Files to omit: ''
[4564 ms] * Fetched feature: common-utils_1_oci version 2.5.1
[4564 ms] * Fetching feature: git_2_oci
[5034 ms] Files to omit: ''
[5035 ms] * Fetched feature: git_2_oci version 1.3.2
[5038 ms] Start: Run: podman-remote buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-kdwk/container-features/0.69.0-1726290810716/Dockerfile-with-features -t vsc-adwaitatemplate-d6e07c129f21728d96321a557ab6c07f289792c57b8c7c17d401ba3107cedd45 --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-kdwk/container-features/0.69.0-1726290810716 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/kdwk/Projects/personal/AdwaitaTemplate/.devcontainer
[1/3] STEP 1/2: FROM swift:noble AS dev_container_auto_added_stage_label
[1/3] STEP 2/2: RUN touch /var/mail/ubuntu &&     chown ubuntu /var/mail/ubuntu &&      userdel -r ubuntu &&     apt-get update &&     apt-get install -y libadwaita-1.0 libadwaita-1-dev
--> Using cache 3d2c6730276ea710e466a242738227b82a6e841b832290862cf77eed046b2a3e
--> 3d2c6730276e
[2/3] STEP 1/4: FROM 3d2c6730276ea710e466a242738227b82a6e841b832290862cf77eed046b2a3e AS dev_containers_feature_content_normalize
[2/3] STEP 2/4: USER root
--> Using cache 9974a1d5e3b1c80649e518044c582b83709f643ef4c475c090c89de264890ef9
--> 9974a1d5e3b1
[2/3] STEP 3/4: COPY --from=dev_containers_feature_content_source devcontainer-features.builtin.env /tmp/build-features/
Error: building at STEP "COPY --from=dev_containers_feature_content_source devcontainer-features.builtin.env /tmp/build-features/": checking on sources under "/tmp/devcontainercli-kdwk/container-features/0.69.0-1726290810716": error in copier subprocess: changing to intended-new-root directory "/tmp/devcontainercli-kdwk/container-features/0.69.0-1726290810716": chdir /tmp/devcontainercli-kdwk/container-features/0.69.0-1726290810716: no such file or directory

[5146 ms] Error: Command failed: podman-remote buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-kdwk/container-features/0.69.0-1726290810716/Dockerfile-with-features -t vsc-adwaitatemplate-d6e07c129f21728d96321a557ab6c07f289792c57b8c7c17d401ba3107cedd45 --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-kdwk/container-features/0.69.0-1726290810716 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/kdwk/Projects/personal/AdwaitaTemplate/.devcontainer
[5146 ms]     at FtA (/var/home/kdwk/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:466:1933)
[5146 ms]     at async Pm (/var/home/kdwk/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:465:1896)
[5146 ms]     at async NH (/var/home/kdwk/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:465:610)
[5146 ms]     at async YtA (/var/home/kdwk/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:482:3771)
[5146 ms]     at async eB (/var/home/kdwk/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:482:4886)
[5146 ms]     at async prA (/var/home/kdwk/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:663:200)
[5146 ms]     at async drA (/var/home/kdwk/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:662:14706)
[5148 ms] Exit code 1
[5150 ms] Command failed: /app/extra/vscode/code /home/kdwk/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/kdwk/.var/app/com.visualstudio.code/config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman-remote --container-session-data-folder /tmp/devcontainers-f79a76fc-bb4f-4a5e-86d4-50d86ce7d1481726290809911 --workspace-folder /home/kdwk/Projects/personal/AdwaitaTemplate --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/kdwk/Projects/personal/AdwaitaTemplate --id-label devcontainer.config_file=/home/kdwk/Projects/personal/AdwaitaTemplate/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/kdwk/Projects/personal/AdwaitaTemplate/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[5150 ms] Exit code 1
```

**Comment by david-swift** [comment] 2024-09-14 08:16
Thanks for opening this issue! @stevestreza, do you know what could cause the problem?

Personally, I rarely use VS Code, but when I do, I build using the [Flatpak extension](https://marketplace.visualstudio.com/items?itemName=bilelmoussaoui.flatpak-vscode), in case you want to try it that way.

**Comment by kdwk** [comment] 2024-09-14 09:14
Using the Flatpak extension to build and run the app works fine in VSCode, it's the actual development that does not work on any IDE I've tried. Gnome Builder doesn't load any diagnostic and code highlighting (despite this working in normal Swift code), while in VSCode the recommended way to develop, the dev container, results in this error.

**Comment by stevestreza** [comment] 2024-09-15 06:41
I can't reproduce the issue here, a fresh clone and rebuild of the container works fine for me, though I'm on NixOS so who knows how that changes the calculation. This is with v0.376.0 of the Dev Containers extension.

The error looks to be related to how VSCode/podman are setting up the container under the hood. I found reference to basically the same error [here](https://stackoverflow.com/questions/76739312/devcontainer-build-error-when-using-podman-with-vscode) (regrettably unanswered). The Dockerfile and devcontainer.json don't appear to do anything that would interfere with those folders.

I would try double checking that VSCode, the Dev Containers extension, any related Docker/Podman extensions, and Docker/Podman themselves are up to date. Otherwise that might be one to file in [Microsot/vscode-remote-release](https://github.com/microsoft/vscode-remote-release/).

I added the dev container because NixOS has some quirks with packaging and loading dynamic libraries like those needed for CodeLLDB and the Swift toolchain. If you're able to use Flatpak for development, I'd recommend using that instead.

**Comment by david-swift** [comment] 2024-10-02 09:11
> Gnome Builder doesn't load any diagnostic and code highlighting (despite this working in normal Swift code)

@kdwk, could you maybe check the line in your Flatpak manifest calling the `swift build` command? Is it `swift build -c debug` or `swift build -c release`? It should be `debug` for developing and `release` for publishing, otherwise, autocompletion does not work in GNOME Builder.

Also, you should compile using the Swift 5 compiler, as it doesn't work at all with the Swift 6 compiler currently (also when compiling Swift 5 code, but this [should be fixed soon](https://gitlab.gnome.org/GNOME/gnome-builder/-/merge_requests/823)). This template is not yet updated to Swift 6, so you probably don't have to change anything.

**Comment by david-swift** [comment] 2024-10-17 19:25
This issue has moved to https://git.aparoksha.dev/aparoksha/adwaita-template/issues/8

**Closed as not planned by david-swift** 2024-10-17 19:25 UTC
